set_property PACKAGE_PIN U18 [get_ports btnc]

set_property PACKAGE_PIN W7 [get_ports {led_segs_n[6]}]
set_property PACKAGE_PIN W6 [get_ports {led_segs_n[5]}]
set_property PACKAGE_PIN U8 [get_ports {led_segs_n[4]}]
set_property PACKAGE_PIN V8 [get_ports {led_segs_n[3]}]
set_property PACKAGE_PIN U5 [get_ports {led_segs_n[2]}]
set_property PACKAGE_PIN V5 [get_ports {led_segs_n[1]}]
set_property PACKAGE_PIN W4 [get_ports {led_sel_n[3]}]
set_property PACKAGE_PIN V4 [get_ports {led_sel_n[2]}]
set_property PACKAGE_PIN U4 [get_ports {led_sel_n[1]}]
set_property PACKAGE_PIN U2 [get_ports {led_sel_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_segs_n[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_segs_n[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_segs_n[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_segs_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_segs_n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_segs_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_segs_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_sel_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_sel_n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_sel_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_sel_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports btnc]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN V7 [get_ports led_dp]
set_property IOSTANDARD LVCMOS33 [get_ports led_dp]
set_property PACKAGE_PIN U7 [get_ports {led_segs_n[0]}]
set_property PACKAGE_PIN U16 [get_ports over_flow]
set_property PACKAGE_PIN V17 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports over_flow]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
